package com.rojatech.java14.records;

// Records are immutable data classes that require only the type and name of fields.
// The equals, hashCode, and toString methods, as well as the private, final fields and public constructor, are generated by the Java compiler.
// a class primarily to hold data (such as results, query results, or information from a service)
public record UserDetail (String name, String mailid)  {
	
}
